### ISSUE TITLE
How to Use My Own Data with the Pretrained Model

### ISSUE THREAD

**Issue by purplestrawberrywatermelon** [TzuchengChang/NASS#6]
Hi, Thank you for providing this pretrained model.
I would like to use this model with my own dataset, but I'm not sure how to properly input my data and obtain results. 
Could you please provide a step-by-step guide or point me to the relevant documentation?

**Comment by TzuchengChang** [comment]
To use your own data, pls refer to the **_speechbrain/recipes/LibriMix/separation/hparams/sepformer-libri2mix-custom.yaml_**. Your data should be organized as shown in the **_custom_** folder in **_readme_**. Specifically, if you just want to infer, then the **_noise_** folder can put the same number of files (just placeholder), if you want to train, then noise data is indispensable.

**Comment by purplestrawberrywatermelon** [comment]
Thank you for your  detailed explanation! I appreciate your help.
